### ISSUE TITLE
Add Schematron to only allow pointers within an edition

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#110]
Write Schematron that only allows `<ptr>`s that link within an edition (forbid `<ptr>`s from linking to other editions/external pages).

**Comment by martindholmes** [comment]
This should be only localCit pointers, right? Also we have the case of documentation pointers.

**Comment by JanelleJenstad** [comment]
Yes, @localCit only -- and we'll need to exclude documentation files from this Schematron.

**Comment by martindholmes** [comment]
There are 350 cases of this, all over the repository. We'll have to look at sample cases and decide what we should do with them. But it seems that people are fond of pointing between editions, and in some cases it seems reasonable (where for instance two editions will be published together in the same anthology, and there is no plan for a print version). Other cases are more strange; pointing from the QME TTR3 annotations to R3 makes no sense, IMHO.

**Comment by martindholmes** [comment]
Since we are supposed to be Linked EMDO, we're presumably on the hook for allowing people to link between things, but the question is what we should do with those links in cases where the linked items are not published in the same anthology (and where the target may not even be published at all). Going a bit Blue-sky with this, we could imagine:

At build time, run a process that enumerates and lists all the texts which have been published in any anthology on the live anthology sites. We might also run this periodically, manually, and store the results in the repo, to save build time.

Whenever there is a link from one text to another which is not in the same edition, first determine whether any version of that text has been published. If so, turn the link into a hard-coded link to the live site.

If there is no published version of the text, check whether the target text is in the same anthology as the text being build (assuming we can come up with some definition of "in the same anthology" for texts which may be in multiple anthologies). If so, we just make a local link. If not, then we just replace the link with "...(forthcoming)." 

How does that sound?

**Comment by LEMDO-PM** [comment]
That sounds fantastic to me! For now, we have documented that people should be using ptr only within their edition (but if we eventually add processing, great!).

On another note, we aren't just using ptr with localCit--those are specific to ASSp, are they not? We have ptrs linking to files and to divs in critical paratexts ([Issue 122](https://github.com/projectLEMDO/lemdoIssues/issues/122)).

**Comment by martindholmes** [comment]
ptr with localCit is a mechanism for causing the build to generate an ASSp reference automatically, so you don't have to figure it out yourself and then update it every time the text is changed in a manner that would make it inaccurate. But no pointer should point outside the anthology, and preferably not outside the edition, unless/until we've agreed on a plan like the above, and figured out the implementation details. We'll wait for @JanelleJenstad's input on that.

**Comment by LEMDO-PM** [comment]
Perfect. Our documentation on using ref vs. ptr matches that :-)

**Comment by martindholmes** [comment]
Is this moribund now? I wonder if I should add a diagnostic to harvest all the cases of ptrs pointing outside an edition, so we can get a sense of how this is working.

**Comment by martindholmes** [comment]
I just did a quick XPath, and I think there are about 420 cases of linking to another text not in the same edition. Example from emdFBFB_M_annotation.xml:

~~~~~
<note type="annotation" target="doc:emdFBFB_M#emdFBFB_M_anc_135" targetEnd="doc:emdFBFB_M#emdFBFB_M_anc_136">
               <note type="label">I am unknown</note>
               <note type="performance">
                  <figure n="Media/Images/FBFB/fbfb01q.jpg">
                     <graphic height="200px" width="150px" style="text-align:left;" mimeType="image/jpg" url="img:FBFB_01q.jpg">
                        <desc/>
                     </graphic>
                  </figure>In the repertory SQM performances, 
<persName ref="pers:HOPK2">Hopkins</persName>’s 
delivery of this phrase echoed his performance of the 
King of Gallia in <title level="m">King Leir</title> 
<quote>We’ll go disguised, all unknown to any</quote> 
(<ptr type="localCit" target="doc:emdLeir_M#emdLeir_M_anc_369 doc:emdLeir_M#emdLeir_M_anc_370"/>). 
His series of characters, the young princes, all share 
a love of disguise. The 
<ref target="doc:qme_SQMPerfInt#qme_SQMPerfInt_p22">cross-referencing of characters</ref> 
in this way was a notable feature of the SQM 
performances.</note>
            </note>
~~~~~

Both these links work perfectly both in lemdo-dev and in qme. Coming at this from another angle, I wonder if a simple link-checker run against a built anthology would be sufficient to catch the problems we're worried about?

**Comment by martindholmes** [comment]
We do now have an anthology-level link-check process, so I'm going to close this ticket.
