### ISSUE TITLE
Are multiple pop-ups allowed?

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#12]
@martindholmes: I have a dim memory of a discussion in which we vetoed multiple pop-ups in LEMDO texts. Do you remember why? Was it aesthetic (clutters up page?) or was it something to do with Endings-compliance?

**Comment by martindholmes** [comment]
It wasn't to do with Endings-compliance; it was because of clutter and bad design. If you have a page with multiple popups, you need to graft on a whole raft of extra affordances so that users can drag them around and bring them on top of each other. Then you have to graft on yet more stuff to handle the problem of them being dragged over other content, and how that content needs to rearrange itself to make itself visible again. 

IIRC the only plausible use-case was people wanting to watch a video while reading the text and clicking on stuff to see the regular popups. We decided that we might make a special case for that, but it's going to eat up programming time and there are a lot of tickets and tasks already in the queue that seem to be more urgent.

**Comment by JanelleJenstad** [comment]
Thanks! I'll close this ticket now. We'll loop back to the video issue in the next two months because QME will want to see some tweaks to the rendering and functionality before they release.
