### ISSUE TITLE
Treat pointers to documentation chapters the same as other pointers in documentation

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#127]
When we have `<ptr>`s linking to documentation chapters in the ODD file, no link is being generated on the site. We would like to treat these `<ptr>`s the same way that we do other `<ptr>`s in documentation (use the content from the target's `<head>` element).

**Comment by martindholmes** [comment]
This was solved ages ago, surely? For example, there is a link in learn_userGuide.html#learn_userGuide_docStructure which points to Chapter 1 (learn_quickStart), and it works fine. learn_quickStart is a chapter defined only in lemdo.odd. @LEMDO-PM if you know of any cases where this is not working, please provide details, otherwise please close the ticket.

**Comment by martindholmes** [comment]
I'm closing this, since there seems to be no actual issue.
