### ISSUE TITLE
Fix numbering in multilevel lists

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#134]
When we have a multilevel list where there is a bulleted list nested inside a numbered list, the numbers skip. See example below from learn_encodeLinks_principles.html. Can we make it so that the numbers don't skip when there is a nested list?
![Multilevel_list_with_numbers](https://user-images.githubusercontent.com/116194494/223830293-aed224fd-befa-4684-977c-dd1080540851.png)

**Comment by pszpak** [comment]
I made it work using css counter. This may have ramifications for screen readers, we'll have to test that.

I spent some time on this and figured out that the rendering you see here above is actually a bug in Firefox. Other browsers should render it correctly.

Normally this would not be a problem, but because LEDMO is outputting divs and then styling them as lists, rather than using the html elements of ul and ol, this bug has emerged (our use of divs as list, especially numbered and nested, is probably very rare).

**Comment by LEMDO-PM** [comment]
I went through a couple of pages on my screen reader this morning and found that it didn't read any of our lists. I wonder if that is because we are using div rather than ul or ol.

**Comment by pszpak** [comment]
Did it completely ignore them or did it create nonsensical output, or did it treat them as just as a bunch of text.

**Comment by LEMDO-PM** [comment]
It just read the text without indicating that it was in a list.

**Comment by pszpak** [comment]
I think we'll add this to it, it'll be in the next build. Can you take a look at it at that point and see if there is a difference?
[https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role](url)

**Comment by LEMDO-PM** [comment]
Yeah, I'll take a look. Do you know why we're using divs rather than ul/ol?

**Comment by pszpak** [comment]
Yes (I asked Martin), it has something to do with the TEI encoding needs. In this case TEI xml allows for p tags to include lists. HTML does not allow this. Work would have to be done to change the built HTMTL,  the XML encoding, or both. It's a larger discussion I think, but an important one.

**Comment by LEMDO-PM** [comment]
Ah, I see.

**Comment by LEMDO-PM** [comment]
@pszpak @martindholmes the aria @roles worked, the screen reader is picking up lists correctly now. Thanks!
