### ISSUE TITLE
Add quotations around pointers to divs

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#135]
As I was proofreading learn_collationTypes I noticed that the `<ptr>` to files renders with quotations while the `<ptr>` to `<div>` elements do not. Please add quotation marks to `<prt>` elements that point to `<div>` elements. 

![image](https://user-images.githubusercontent.com/112907741/224846915-91d8ffbc-4da1-4b19-b95e-d21db4c634a7.png)

**Comment by martindholmes** [comment]
There's a valid question here: if an article title gets quotes (because it's an analytic), do we also put quotes around the title of a subsection of an article? I don't know of any styleguide that addresses this, so I don't know what the answer should be. But if everyone is agreed that we treat subsections and sub-subsections as though they are individual articles, then I can easily add the quotations. @mahaylagalliford @JanelleJenstad @LEMDO-PM what do you think?

**Comment by LEMDO-PM** [comment]
Good point Martin! I'm digging into MLA and Chicago right now and here's what I've found:

MLA (9th ed.) says that "Columns and titled categories in periodicals and on websites" don't get formatting. Their example is the category of Ask the MLA on their website. In my mind, that could potentially correspond to our `<div>`s in documentation such as our Practice or Step-by-Step sections, but wouldn't correspond to sections in critical paratexts, which are more unique. It also says "Terms designating divisions of a work" don't get any additional formatting (so chapter 2 doesn't get quotation marks when integrated into prose). That said, a chapter **title** would get quotation marks around it.

Chicago says in "8.177: Articles, stories, chapters, and so on" that "individual selections" in books get quotation marks. In "8.180: Numbered chapters, parts, and so on", it says that if we are incorporating parts with numbers into prose, there would be no quotation marks. One example that they give is "Turn to section 5(a) for further examples."

My gut reading all of that is that because the sections have titles and we want to refer to the sections using their titles when we link to them with `<ptr>`, they should get quotation marks around them. When we just mention something by number rather than title, we would be using the `<ref>` element anyhow and can just not include a `<title>` element.

**Comment by martindholmes** [comment]
Based on that, and on the fact that with the current structure of our documentation it's by no means clear what constitutes a chapter or a section, I think quotes all round, then. Will do.

**Comment by martindholmes** [comment]
First shot at a fix committed in rev 12791. We'll see if anything breaks. :-)

**Comment by LEMDO-PM** [comment]
Great, thanks :-)

**Comment by martindholmes** [comment]
Looks like this first shot didn't work. I'll have to investigate further. The documentation is such a gnarly nest of stuff that it's impossible to build a single page locally to test things.

**Comment by martindholmes** [comment]
I've committed what I believe to be a working fix in rev 13042. If all is well this can be closed.

**Comment by martindholmes** [comment]
All seems well; giving the team a little time to check for any anomalies, but if nothing shows up this can be closed any time after 2023-05-05.
