### ISSUE TITLE
ASSp processing question for spans of text

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#137]
In emdH5_GenIntro, we have a long quote that spans two speeches. We're using a single `<ptr>` element to link back to emd H5_FM. Here is how it is encoded: `<ptr type="localCit" target="doc:emdH5_FM#emdH5_FM_a4_s7_sp22 doc:emdH5_FM#emdH5_FM_a4_s7_sp23"/>`. On the site, only the first speech is rendering in the citation.
![image](https://user-images.githubusercontent.com/116194494/225460828-66581acb-c91a-47bd-87b5-0077d468df68.png)
Is that what we would expect with this encoding? Do we need two `<ptr>` elements? Or would we expect it to render showing both ASSp numbers?

**Comment by martindholmes** [comment]
I don't think we had considered the possibility that spans stretching across speeches would be linked.

**Comment by martindholmes** [comment]
@LEMDO-PM Are these rare cases which only span two speeches? If so, I think I would create two separate pointers, one pointing to each speech, and put a hyphen between them.

**Comment by martindholmes** [comment]
Ping @LEMDO-PM...

**Comment by LEMDO-PM** [comment]
@martindholmes, I don't expect that this will be the only instance, but it seems to be relatively rare. I can do a search later on this week to find out how often it's currently occurring.

**Comment by martindholmes** [comment]
Since it would be very problematic to process this, and conversely it's very easy for the editor to create two separate pointers, I think this should simply be a task to update the documentation to make this clear: if you're annotating a span of text which runs across the boundary between ASSP units, then create your citation using two distinct pointers with a hyphen between them.

**Comment by LEMDO-PM** [comment]
That sounds good. Thanks!! I've added it to my documentation list.
