### ISSUE TITLE
Put A.S.Sp in right margin of speech prefix in PDF

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#14]
@martindholmes (on Issue 7) wrote:  "On the issue of the PDFs, I think it would be a mistake to put the speech numbers in the left margin. In order to do that, the entirety of the text needs to be shifted to the right, which will dramatically increase the page count. Instead, I suggest that we put the abbreviated form (1.1.Sp1) in the right margin where the line numbers already go, but next to the speech prefix; since speech prefixes aren't counted as part of the line-count, that line in the right margin is guaranteed to be empty. That should ensure that only empty space is used, so the page-count doesn't rise, and since speech prefixes are typically shorter than regular lines, we should never run into overwrite collisions."

**Comment by martindholmes** [comment]
I've actually already done this, but the result is that the layout is screwed because assps are longer than line-numbers. The fallout is that I'll have to re-work the entire page layout, which was already close to breaking anyway (text too close to the paper edges), and there's no simple way to do what we need to do for that, so I'll have to do a lot of experimentation and testing of various LaTeX packages to get to a solution.

**Comment by martindholmes** [comment]
I think this can be closed, with any further adjustment being part of the overall PDF styling.
