### ISSUE TITLE
Add alpha site for EMEE

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#140]
Please create an alpha site for EMEE. Their student programmer is ready to start working on CSS and menus :-)

EMEE is an encyclopedia project from the old Shakespeare's Life and Times, so it won't have any editions to add to the site.

**Comment by martindholmes** [comment]
@LEMDO-PM Please see my comment on Teams.

**Comment by martindholmes** [comment]
I think we need to plan this carefully. It seems to me that EMEE is going to be more similar to documentation than to regular anthologies. The need to be able to include random pages from EMEE in any anthology means that linking between pages will have to be carefully managed, otherwise pulling in a single page from EMEE into another anthology could result in the entirety of EMEE being included, which is obviously not ideal. What might be better is to structure entries in EMEE such that an anthology could include a sort of explanatory short abstract from any EMEE entry, which would not contain links or references to other content, and then EMEE itself could include a much longer full entry, linked to other EMEE resources.

**Comment by JanelleJenstad** [comment]
Email from @martindholmes on 2023-04-11: "I see a lot of content and activity in EMEE so I've added it to the set of anthologies that gets built on Jenkins even though it's not technically in buildable status. I don't know whether it will succeed or what it will look like when it's done, though."

The EMEE anthology did not succeed in building. I am perplexed because LEMDO-dev builds without any editions.

**Comment by martindholmes** [comment]
Are its anthology file and home page (inside that file) published? If not then there's nothing to build.

**Comment by martindholmes** [comment]
No, I see it's not that; the two anthologies look pretty similar. I'll see if I can figure out the issue.

**Comment by martindholmes** [comment]
I found a minor difference in the configuration file on Jenkins, so I'm running another build to see if that fixed it.

**Comment by martindholmes** [comment]
Now the problem is caused by the fact that the EMEE site template looks nothing like what a template should look like; it doesn't have the right content or ids. A site template has to contain all the precise page components the build process is looking for, in the right structure and with the right ids.

**Comment by JanelleJenstad** [comment]
I'll have a look at it. Whatever is there is what I made for them as a template, I think.

**Comment by JanelleJenstad** [comment]
I've reworked their sitePage by modelling it on the lemdo-dev site page. @pszpak did some work on the lemdo-dev site page. I hope it's appropriate to include that work in the anthology site pages.

**Comment by martindholmes** [comment]
Absolutely. The ideal is to start from the lemdo-dev page, and then only change specific things that need to change.

We should probably have a Schematron file for validating sitePage.html because it's very easy to break the build process by deleting something you didn't know was necessary, or changing an id that's being used by the build process.

**Comment by JanelleJenstad** [comment]
Okay, let's see if I've fixed things or made even more of a mess!  @LEMDO-PM: If I've succeeded, we could make a sitePage template by starting with the lemdo-dev site page (but let's ask Pat if he's completely finished with lemdo-dev first).

**Comment by martindholmes** [comment]
In local testing, it's reporting that the sitePage.html file is invalid. I'll see if I can fix it.

**Comment by martindholmes** [comment]
It doesn't look like the lemdo-dev site page at all; there seems to be a bunch of stuff missing. Trying to figure it out.

**Comment by JanelleJenstad** [comment]
I took out most of the lemdo-dev menus, so the emee sitePage is considerably shorter.

**Comment by martindholmes** [comment]
I think you took out the main container for the page content too, along with the asides (popout tabs) and a bunch of other stuff. If there's no main element, there's nowhere to put the content of a page, and if there's no popout thing, nobody will get any credit for anything. :-) I'll try putting those back.

**Comment by martindholmes** [comment]
I think this is working now, so I'll close the ticket.
