### ISSUE TITLE
Add Douai images to /lemdo/facsimiles/douai

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#141]
@martindholmes: I have saved the Douai images in a zipped folder in my UVic OneDrive. I've used the OneDrive filesharing privileges to share the zipped folder with you. When you are back in Victoria, please add the images to lemdo/facsimiles/douai in the HCMC drive.

**Comment by martindholmes** [comment]
Will do. Not practical over bad wifi probably, so it'll be after I get back.

**Comment by JanelleJenstad** [comment]
@martindholmes: Hold off on this task. The set of images the Douai folks gave me was not complete. We are redoing the transfer.

**Comment by martindholmes** [comment]
🙂

**Comment by JanelleJenstad** [comment]
I now have the complete set of images and have resent the link to the place where I've saved them in UVic OneDrive. Please go ahead when you are back home.

**Comment by martindholmes** [comment]
@JanelleJenstad As requested they're at facsimiles/douai/, but there is also an older facsimiles/Douai (upper-case) from February which has four images in it. Since the texts are at texts/douai (lower-case), I suggest we remove the older folder to avoid confusion and keep the lower-case one, but if you'd prefer to rename the newer one to Douai after deleting the old one, let me know.

**Comment by JanelleJenstad** [comment]
Please remove the old folder and keep the lower-case one. Thank you!

**Comment by martindholmes** [comment]
Done! Closing this.

**Comment by JanelleJenstad** [comment]
Merci beaucoup de l'equipe Douai!
