### ISSUE TITLE
Apply current OS styling to documents with lbf:folio

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#151]
See #105. I'm breaking out a step from closed ticket that was deemed too broad. 

The styling for semi-diplomatic transcriptions (old-spelling) is working beautifully for quartos -- i.e., files with let:oldSpelling and lbf:quarto. Could we please apply this stylesheet to files with let:oldSpelling and lbf:folio just to see what happens? 

I'm hoping that we will not need to make many changes to the quarto stylesheet in order to render the folios well, but I need to see the output from the stylesheet to know how much work lies ahead. (Also, applying the stylesheet will speed up the proofing for the RAs working on folios.)

**Comment by martindholmes** [comment]
@JanelleJenstad I was struggling for a while to find any link between lbf:quarto and lbf:folio and any styling at all, until I realized it should be cat:lbfQuarto and cat:lbfFolio. :-)

However, there is no XSLT or CSS that is triggered by lbfQuarto or lbfFolio. The style rules are focused on "BornDig", "Primary", and "letOldSpelling"; no other `catRef/@target` value is mentioned or used. So if the folios and the quartos are rendered differently, it's presumably because there's lots of style in the quarto files which isn't in the folio files. If you can point to a pair of texts with the same XML and rendition settings which are coming out differently, we can try to figure out why that is.

**Comment by LEMDO-PM** [comment]
I think I've got this fixed--Part of the issue was with encoding, part was with the `<lb>` rendering, which will be fixed when we change to wlns. We can close this issue.
