### ISSUE TITLE
Page beginning not showing up on site

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#158]
We have a `<pb>` element in emdMucd_Q3 that is not showing up. It is encoded (correctly) as `<pb n="A4r/>`, which matches the encoding of the other `<pb>` elements (which are rendering as expected on the site).

We want it to render the same as the other `<pb>` elements (the horizontal line a "page beginning" text).

**Comment by martindholmes** [comment]
@LEMDO-PM Fix committed in rev 13524. There may be some fallout from this change, but if we don't see a build break and we don't notice any issues in the next little while we can close this. The `@class` attribute was being stripped from the div at a post-processing stage due to some surrounding context; I don't know why that was being done, and it doesn't seem logical, so I've just prevented it. That gives us back the page division in the rendering. Whether it hurts anything else remains to be seen, but if so, we should deal with that problem in a different way.

**Comment by martindholmes** [comment]
Closing this since we haven't seen any negative fallout.
