### ISSUE TITLE
add styling to running title

### ISSUE THREAD

**Issue by mahaylagalliford** [projectLEMDO/lemdoIssues#163]
Please retain italicization for running title. Please text align centre.

Running titles are encoded as `<span data-el="fw" data-type="runningTitle">`.

Example: Please see emdH5_Q1. Search: The Chronical Historie.

**Comment by martindholmes** [comment]
@mahaylagalliford @pszpak  If this is for a semi-diplomatic text, then surely this SHOULDN'T be done by default. Every text will be different. It's up to the encoder to determine what style is appropriate for running titles in that text, and then to create a rendition element to apply it. Deviations from the normal rendition should then be handled using a local `@style` attribute.

**Comment by LEMDO-PM** [comment]
@martindholmes Because the vast majority of those that we have seen fit this format, we feel comfortable adding the generic styling so that not every file needs to add the same stuff to the `<tagsDecl>`. For those that don't fit the centered and italic formatting (I've come across a couple where a page or two with roman type on running titles), people can add `@rendition` or `@style`

**Comment by martindholmes** [comment]
@LEMDO-PM This is pernicious; it means that the standalone XML files for the semi-diplomatic texts will be missing crucial information. Remember that we are trying to describe the original document in the XML. This is nothing to do with how we might decide to render it later. You can't do XML encoding through render-time CSS. Please don't do this.

**Comment by LEMDO-PM** [comment]
@martindholmes We will do this in the `<tagsDecl>`. Thanks for catching that!
