### ISSUE TITLE
Processing for using ptr to link to anthology about pages?

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#177]
EMEE is trying to encode links to about pages from about pages and would like to use the `<ptr>` element to do so. These `<ptr>`s aren't working, though they are encoded correctly. For an example, see emee_culture_court.

Do we have processing to use pointers to link to anthology about pages? If not, please add processing. We would want pointers to anthology about pages to render with the page's title as its text.

**Comment by martindholmes** [comment]
Strange; this is working fine in regular texts -- there's a working instance in emdJC_GenIntro.html#emdJC_GenIntro_HImageryandSymbolism. I think there's something weird going on here.

**Comment by martindholmes** [comment]
Ah, figured it out: This pointer expansion process was put in place ONLY for documents whose id starts with "emd". @JanelleJenstad @LEMDO-PM There must have been a reason for this restriction, since it's quite explicit: only emd docs are allowed to use this kind of pointer, and they're only allowed to use it to point to OTHER emd docs. I can remove these limitations easily enough, and I'll do that now, but I would like to know why they were in place in the first place; it's not something I would have done for no reason. Can you remember what your rationale for the limitation was? I think it might be something to do with not breaking the similar-but-slightly-different processing that's in place for documentation.

**Comment by martindholmes** [comment]
Fix committed in rev 14044. There may well be fallout from this, though; I think that restriction was there for a reason.

**Comment by JanelleJenstad** [comment]
I have a dim memory of this -- I believe that we did it to prevent people from using `<ptr>` to make links outside their edition ... but it's not super useful because it doesn't prevent people from linking to unpublished editions or editions outside their anthology (all of which have files starting with emd).

**Comment by martindholmes** [comment]
@JanelleJenstad That was probably it. It seems there's no way to police what people will link to in any mechanical way, hence my tool for checking links in anthologies, but that's waiting on a full solution to issue #170 before we can really make use of it.

**Comment by martindholmes** [comment]
I claim this is fixed in the latest build, and I can't see that anything broke.

**Comment by LEMDO-PM** [comment]
@martindholmes, the EMEE team has sent thanks your way for this. They looked at their dev site with the new build and say "all the ptr​s are working now. This is super helpful!" :-)
