### ISSUE TITLE
Suppress round brackets around inline stage directions in QME modern texts

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#183]
Question for @martindholmes:
You may recall that LEMDO's Textual Advisors wanted to _not_ put square brackets around editorially supplied stage directions. They have good reasons, not least of which is that square brackets were proposed by McKerrow in his _Prolegomena to the Oxford Shakespeare_ in the 1930s as a way of saving space in the collation. We don't need to save paper because we are not on the eve of a world war (or maybe we are -- but paper supply is the least of our worries), and we DO want a full collation. So the DRE Co-Coordinating Editors (who are coterminous with the LEMDO Textual Advisors) asked us to suppress the `<supplied>` elements around editorially supplied stage directions.  

THEN, DRE asked for round brackets around inline stage directions because they looked weird floating like italic islands in the middle of the speeches without the square brackets. 

So now we have a situation where QME has both round and square brackets, the round ones from our processing for inline stage directions and the square ones from our processing of the `<supplied>` elements. They want to keep the square brackets and lost the round ones. 

Is that something we can customize at the anthology level?

<img width="482" alt="image" src="https://github.com/projectLEMDO/lemdoIssues/assets/5943608/79e9d7ea-0c4a-4c53-a0a3-addf0fc2cb1e">

**Comment by martindholmes** [comment]
Not really doable at the anthology level. They'll all have to agree amongst themselves what they would like to do. The only option for flexibility would be to provide them as CSS before: and after: values rather than hard-coded text in the output, but that means if you select/copy/paste the text containing them, they're not included. If the Board as a whole would like to switch to CSS-only brackets, we can do that.

**Comment by JanelleJenstad** [comment]
Actually, I think I've figured out a way to compromise. In `xhtml5_templates_tei_module.xml`, we could make a tweak so that the parentheses are added in case where `<stage>` is a child of `<l>` or `<p>` but not if `<stage>` is the parent of `<supplied>`  and `<supplied>` is the immediate child of `<stage>`. On the `@test` attribute, we need `"ancestor::l[not(contains(supplied)] or ancestor::p[not(contains(supplied))]"` or something like that (my XPath is not good).

This is what we have now in the XSLT: 
`<xd:doc>
    <xd:desc>Stage elements. If a stage element is inline (inside a line element), it will 
    have wrapping parentheses.</xd:desc>
  </xd:doc>
  <xsl:template match="stage" mode="tei">
    
    <xsl:variable as="xs:string*" name="classSeq" select="local-name(),@type"/>
    <xsl:variable name="elName" as="xs:string" select="if (descendant::list) then 'div' else 'span'"/>
    
    <xsl:element name="{$elName}">
      <xsl:call-template name="processAtts">
        <xsl:with-param name="classes" select="$classSeq" as="xs:string*"/>
      </xsl:call-template>
      <xsl:if test="ancestor::l or ancestor::p"><xsl:text>(</xsl:text></xsl:if><xsl:apply-templates mode="#current"/><xsl:if test="ancestor::l or ancestor::p"><xsl:text>)</xsl:text></xsl:if>
    </xsl:element>
  </xsl:template>`

**Comment by JanelleJenstad** [comment]
I will follow up with QME to explain that (round parentheses) signify inline stage direction and that square brackets signify supplied material. The round parentheses are necessary because italicization along is not an unambiguous signifier in a context where italicization is also used for foreign words.

**Comment by martindholmes** [comment]
@JanelleJenstad Just following up on the XPath: here:

`"ancestor::l[not(contains(supplied)] or ancestor::p[not(contains(supplied))]"`

you're using contains(), which is a string test -- in other words you're checking whether the text content of the element contains the word "supplied". This would be the test:

`"ancestor::l[not(descendant::supplied] or ancestor::p[not(descendant::supplied)]"`

It would still be problematic because there are cases where the descendant supplied element is not coterminous with the stage element, so a better (or additional) check might be:

`normalize-space(.) = normalize-space(descendant::supplied)`

which would check whether the effective text content of the stage element is identical to the effective text content of the supplied element.

**Comment by martindholmes** [comment]
@JanelleJenstad Where are we at with this one? Should we go ahead with the change?

**Comment by JanelleJenstad** [comment]
Yes please, if it's do-able!

**Comment by martindholmes** [comment]
Implemented in rev 15486. If all is well, this can be closed.
