### ISSUE TITLE
No ToC is generated for supplementary texts

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#188]
There is currently no table of contents being generated for supplementary texts (see emdJn_Holinshed and emdPer_Appolonius). Please generate ToC from div heads. We would like it to be the same as how we have critical paratext ToCs.

**Comment by martindholmes** [comment]
@LEMDO-PM emdJn_Holinshed  is diplomatic/primary, and therefore the TOC is to be constructed using pb elements. If you want a TOC as in a critical text, then it can't be a primary source text. However, I've now added a check to see if there are any pb elements in the primary source, and if there aren't, then it default to using div[head] instead. So that works for these two texts at least. Fix in rev 14971.

**Comment by martindholmes** [comment]
If build is good, this can be closed.

**Comment by martindholmes** [comment]
All good. Closing.
