### ISSUE TITLE
Check rendering of foreign languages and tweak if necessary

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#19]
In emdPer_Appolonius.xml, we have a number of paragraphs with an `@xml:lang` attribute and the value `la`.

```
<p xml:lang="la">
            Qualiter Appolinus in cena recumbens nihil comedit, sed, doloroso vultu, submisso capite, maxime ingemiscebat; qui tandem a filia regis confortatus citheram plectens cunctis audientibus citherando vltra modum complacuit.
            </p>
```
They are not rendering in italics but we would like them to be rendered in italics.

The question to @martindholmes is whether we should:

1. Wrap all of these in a `<foreign>` element to make the processing easier, or
2. Have you write processing that italicizes `<p>` elements with xml:lang that is anything other than `en`.

Notes:

1. Our documentation does say that one can use `@xml:lang` on `<p>`. 
2. Navarra has tried wrapping the text in `<foreign>` and it still wasn't rendering in italics.
3. This particular file is a supplementary text (with docType `letModernSpelling` and `ldtPrimary`, which may be the source of the problem.

**Comment by martindholmes** [comment]
I don't think we have any specific handling for foreign languages, so I wouldn't expect to see any output whatever you do. I think the issue of what language is being used is distinct from the issue of whether you want to render it as foreign; there are lots of cases where (for example) Latin is used but shouldn't be italicized because e.g. CMOS says "Commonly used Latin words and abbreviations should not be italicized."

So I think it makes sense to use the `<foreign>` element, and it would be best to put the `@xml:lang` on that element, I believe.

However, we already have a pattern that's in common use:

~~~~~
<foreign rendition="rnd:italic" xml:lang="la">Memento Mori</foreign>
~~~~~
(emd1H4_F1)

and we also have:

~~~~~
<foreign xml:lang="it">bona robas</foreign>
~~~~~
(emd2H4_M)

The former renders in italics, and the latter doesn't. So I think we should probably make a policy for this. If people have used the `<foreign>` element with and without a rendition attribute on purpose to distinguish between text that they do and don't want to see in italics, then we don't want to bork that by making all `<foreign>` elements italic by default.

**Comment by martindholmes** [comment]
@JanelleJenstad What do you think we should do on this ticket? Thinking about it, the options are:

1. Stick with the current system, where `@rendition` is used when italics are required.
2. Make all instances of `<foreign>` show in italics. There are 2890 of these in the collection; 626 of them have `@rendition`, and of those, in 312 cases the `@rendition` contains "italic". So we can expect the rendering of about 2500 instances to change without warning if we do this (although some of them may already be italic through some other mechanism).
3. Investigate to figure out why `<foreign>` would be used without italic rendering, then decide on a general styleguide rule and impose it on every case.

**Comment by JanelleJenstad** [comment]
In modern texts, <foreign> should be italicized by default. Do not use renditions on `<foreign>`.

**Comment by martindholmes** [comment]
1. Make all `<foreign>` elements render in italic in modern texts.
2. Remove `@rendition` italicization components from modern texts.
3. Leave `<foreign>` elements alone in OS texts.
4. Create a diagnostic which lists all cases where the text is letOldSpelling or letMixed,  and an `@status` value of IML=TEI_INP, because these must be fixed before we can add Schematron.

**Comment by martindholmes** [comment]
I've done #1 and #2 in rev 9971. I found only 7 cases of a `<foreign>` element with `@rendition` for italic in letModern texts. #3 is no-action, so that leaves just #4. I'm not sure about exactly what we meant to achieve with #4: @JanelleJenstad can you remember exactly what we wanted to know and why?

There is one case of a rendition on a foreign element which is designed to centre it. in FBFB_M, but I think that case is a trailer from the OS text which should not even be in the modern version.

**Comment by JanelleJenstad** [comment]
Lots of modern editions include trailers (e.g., FINIS is very commonly included in modern editions). So let's leave FBFB_M as is. 

I can't remember why we needed a list before we implemented Schematron, unless I wanted to change <foreign> to <hi rendition="rnd:italic"> OS texts before you implemented the rule. Transcribers shouldn't be making judgement calls about foreign language in OS texts; we should just be capturing the fact that something is italicized. Foreign languages in playbooks are really complicated. Sometimes they're just stage gibberish, so wrapping <foreign> around them is a judgement call best left to the editor of the modern text.

**Comment by JanelleJenstad** [comment]
I think we can close this ticket now. We are happy with '<foreign>' not being rendered in italics and having editors add a rendition attribute if they want it to italicize.

**Comment by martindholmes** [comment]
Closing this -- I think it got missed.

**Comment by martindholmes** [comment]
Decision reversed at LEMDO meeting 2022-10-26: All foreign elements should be rendered in italics, and people that tag things that shouldn't be italic will be told not to tag such things as e.g. "ad hoc".

**Comment by martindholmes** [comment]
I believe this is now working.
