### ISSUE TITLE
`<objectName>`: usage, rendering, and linking

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#193]
From issue #2 we have now added `<objectName>` to the schema, and we have one instance of using it, in emdTRIU2_M. Three questions:

1. Should it have any default rendering (italics or whatever) in modern texts? (There is none at the time of writing.)
2. Will it need to be linked to something in a listObject in e.g. OBJS1.xml, or is it purely an inline classifier?
3. Who will write documentation for it?

**Comment by JanelleJenstad** [comment]
Note that this element will give us something to which we can convert the old IML `<PROP>` element. 

1. No default rendering please.
2. It will be linked to the xml:id of an `<object>` in a listObject. I was hoping to include a `<listObject>` in the `<particDesc> `but see that it's not allowed there. It's allowed in `<msDesc>` but that doesn't make sense for us. (It really should be a member of `model.orgPart`). Another option is to make a OBJS1 file. There's some merit to a centralized OBJS1 file because we know that playing companies reused props and set pieces ... but it would work better at the anthology level. We don't have any anthology-level database-like files, however. I am stumped.
3. I will write documentation.

**Comment by martindholmes** [comment]
@JanelleJenstad We link to e.g. person or org elements because a) they're unique in the world, and b) we have something to say about them. However, it seems to me that the intended use of objects is not like that; when you tag (say) a sword in Hamlet, you're not tagging a specific unique thing; you're tagging a species of thing. That suggests to me that you don't actually need a listObject; what you need is a taxonomy. A sword in a play is only interesting/taggable if it's to be associated with other tagged swords in other plays; that would enable people to search for (say) plays with lots of mentions of swords. But it has no properties in itself, unlike a person or an org, because it's not a real thing.

Using a taxonomy also lets us nest categories so we can establish a true hierarchy of object types.

**Comment by JanelleJenstad** [comment]
Good thinking. I'll confer with @LEMDO-PM next week about the original use case and make a different plan. 

I'll close this ticket and open another one (#194)
