### ISSUE TITLE
orgName not working in Doaui anthology

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#202]
The `<orgName>` element is not working as expected in the Douai anthology. It creates a link, but nothing happens when you click on it. `<orgName>` is working on LEMDO-dev and other anthologies (e.g., it works in QME both on the dev and the published site).

For examples, see douai/site/about on their dev site, click on the hamburger menu and then credits. LEMDO Team is encoded using `<orgName>` in the `<teiHeader>` there. For an example in the `<body>` of a file, see para4 of the same page. Both of these examples are working on LEMDO-dev.

**Comment by martindholmes** [comment]
The LEMD1 org information is in the appendix of the page as it should be, so that's not the problem. I wonder if the Douai team mistakenly copied the original lemdo.js code into their douai.js file, overriding the code that's already in the page from lemdo.js, but then failed to keep it updated so it hasn't inherited the bugfix I made quite a while ago for org links. There is no need to reiterate the JavaScript from the lemdo.js file in the douai.js file unless you explicitly want to suppress/change/replace it. I would try removing all the code from line 385 onwards in douai.js so that the original updated lemdo.js can work again.

**Comment by martindholmes** [comment]
@comesaignol I've tested this and I can confirm that it that extra code starting from line 385 is removed, org links work perfectly. I don't see any other problems resulting from this change. Assuming that the Douai team have not added any of their own custom JavaScript mixed in with the copy of the original lemdo.js, this is an easy fix.

**Comment by martindholmes** [comment]
I've confirmed that lines 385 onwards of the douai.js file are simply a copy of most of the original lemdo-dev.js file, lacking recent updates and an init function. So I'm going to just delete those lines to solve this problem.

**Comment by martindholmes** [comment]
Fix committed in rev 16822. If all builds OK, this issue can be closed.

**Comment by LEMDO-PM** [comment]
Thanks!
