### ISSUE TITLE
Develop encoding model for interrupting speeches

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#231]
We have a speech by Ferdinand in LLL F1 with persistent interruptions by the Clowne (Costard). The interruptions are inserted into the speech parenthetically (see image that Sofia will upload) with a speech prefix and the brief speech (_Clo_ Me?).

I'd like an encoding practice that respects the mise-en-page while allowing us to track speeches. 

We'll also need to figure out a numbering protocol. My first instinct is to use `<spGrp>` ... and to not number the interruptions but rather number the container `<spGrp>`.

**Comment by sofiawilson** [comment]
![Screenshot from 2024-06-04 14-25-11](https://github.com/projectLEMDO/lemdoIssues/assets/157427369/a8cfcb29-2a9e-421a-8156-fd85e91692de)

**Comment by martindholmes** [comment]
We could devise something like sp type="inline", but our biggest problem would be that TEI sp cannot be a child of p or l or sp or anything else that might constitute the content of the container speech, so you can't actually reflect the nesting here. This is the problem with semi-diplomatic: if you're going to be at all undiplomatic in the sense of deciding you will identify some things as e.g. speeches, speech-prefixes, and all that, then you're electing to apply the abstract content model to the text, and with that come hierarchical constraints. So for encoding, I would recommend actually splitting the container speech around the contained speeches, and using `@next` and `@prev` as we do for other hierarchy violations. That will also make it easier to proof, I think, and to convert to a modern text. We would have to add some signal that the contained speeches are marked off with parentheses (in this case -- maybe not in others), so that the rendering can be faithful. Maybe `<sp type="inline" subtype="parenthetical">`. But of course sp is not a member of att.typed, so maybe it'd have to be something like `<sp rend="inline_parenthetical">`.

But the rendering will be a bit gnarly. That'll be a long day.

**Comment by JanelleJenstad** [comment]
Thanks for the suggestion, @martindholmes. I'll mock up some encoding and put in a ticket for processing.

**Comment by LEMDO-PM** [comment]
Done. We have a ticket in with TEI, and styling looks correct
<img width="769" alt="image" src="https://github.com/user-attachments/assets/acffd6ab-8495-497b-8c61-bfd8ac29a4c1">
