### ISSUE TITLE
DRE: Add table sorting to dre_editionsProgress

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#238]
Please add table sorting to dre_editionsProgress

**Comment by JanelleJenstad** [comment]
@martindholmes: I would like to learn how to make tables sortable. Would you please teach me?

**Comment by martindholmes** [comment]
We need to add the little sorttable.js file to the lemdo-dev repo and then devise a method for an encoder to specify that it should be invoked. Not difficult.

**Comment by martindholmes** [comment]
Question: should all tables in specific types of documents be sortable by default, or should this always be invoked using a specific encoding mechanism? For example, we could make all tables in documentation sortable by default, rather than confronting the reader with puzzling situations where one table is sortable but the next one isn't. Are there contexts in which tables should not be sortable?

**Comment by JackWilton1594** [comment]
I can't think of any reason why all tables shouldn't be sortable.

**Comment by martindholmes** [comment]
OK, I'll implement that.

**Comment by martindholmes** [comment]
Tables can't be sortable unless they have column headings (meaning that in the TEI their first row has to have `@role="label"`). So for instance this table can't be sortable:

dre_eg_emendation.html

whereas this one can:

dre_editionsProgress.html

**Comment by martindholmes** [comment]
I also wonder whether chronological tables like this:

emdJC_Chronology.html

should be sortable, but I've gone ahead and made all viable tables sortable in rev 18173.

**Comment by martindholmes** [comment]
@JanelleJenstad All you need to do to make a table sortable, then, is to ensure it starts with a row with `@role="label"`.

**Comment by JanelleJenstad** [comment]
Thank you!

**Comment by martindholmes** [comment]
I think this can be closed now.
