### ISSUE TITLE
Tweak keyboard shortcut for inserting a respStmt

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#239]
The keyboard shortcut for inserting a respStmt inserts this template TEI:
`<respStmt>
               <resp ref="resp:">[desc]</resp>
               <name ref="pers:">[name]</name>
            </respStmt>`

Since we made this shortcut, we decided to use `persName` instead of `name`. Could we please update the shortcut to insert this template:

`<respStmt>
               <resp ref="resp:">[desc]</resp>
               <persName ref="pers:">[name]</name>
            </respStmt>`

I would like to learn how to add keyboard shortcuts myself. Let's take this as a teaching opportunity for me and Navarra.

**Comment by martindholmes** [comment]
In Oxygen, go into Options/Preferences, and type "Code Templates" to find the Code Templates panel. Find LEMDO: Insert respStmt, select it, and choose Edit. Modify the template code as required, and then press OK, OK, and you're done. The templates are stored in the lemdo-all.xpr file, so that will have to be committed for everyone to inherit the change.

**Comment by JanelleJenstad** [comment]
Thanks for the instructions! I've made the changes and committed lemdo-all.xpr.
