### ISSUE TITLE
PDF: Include full ASSP reference in running header?

### ISSUE THREAD

**Issue by martindholmes** [projectLEMDO/lemdoIssues#256]
@JackWilton1594 suggests:

"Running header: can we expand the reference appearing after the play title to include the appropriate act/scene? For example, rather than "An Humorous Day's Mirth: 2", we'd have "An Humorous Day's Mirth: Scene 2", and so on."

Another policy decision, but bear in mind that running headers must always fit on a single line; if the play title is long, and we then have Act 1 Scene 4, it could end up too long. This is not a problem with any of the PDFs we're currently building, though.

**Comment by JanelleJenstad** [comment]
For plays with long titles and with acts/scenes, we might run into trouble.

**Comment by JackWilton1594** [comment]
The alternative is to give the full ASSP in the margin. At the moment, print readers need to check the running header (only on the recto, which is problematic) and then add this information to the Speech number in the margin. I'd prefer we kept the running headers simple – title on recto, URL on verso – and gave the complete ASSP in the margin – in X.Y.SpZ format, without expanding to AcX ScY SpZ – assuming that's feasible?

**Comment by JackWilton1594** [comment]
As a compromise, I think we should include the Act Scene information on every running header, not just the recto, and replace the URL with the title of the play. If we're being fancy, we could alternate the location of the Act Scene info on recto/verso, as they do here in the OWC _Romeo and Juliet_ as an example:
![Screenshot 2024-07-31 at 19 56 39](https://github.com/user-attachments/assets/67f18f98-61e8-4327-a534-c106131a66cd)
![Screenshot 2024-07-31 at 19 56 44](https://github.com/user-attachments/assets/58bfacf7-1dad-4f72-86f4-95e912aac641)

Otherwise, just keeping it simple and centered immediately following the play title is perfectly fine.

That way, nobody has to flip pages to figure out where a speech occurs!

B

**Comment by JanelleJenstad** [comment]
(Consensus achieved.) This means removing the URL from the running title; I'm okay with that (because there will be a page about the digital edition -- still to be added to the print build). I agree with Brett's suggestion that we have the play title and the scene number. For texts that have just one level of division (e.g., scene, sonnet), please do Sc.1, Son.1, etc. For texts that have two or more levels of divisions, please reproduce just the numbers (1.1, 1.2, 2.1, 2.2, etc).

**Comment by JanelleJenstad** [comment]
Related to #251.

**Comment by martindholmes** [comment]
I think this is done, as part of the work on #251.

**Comment by martindholmes** [comment]
Since no-one has raised any objections, I'm going to close this.

**Comment by JackWilton1594** [comment]
@martindholmes Sorry for not checking this until now.

I notice the PDFs are still rendering the title on verso pages and the A/S reference on recto pages of the modern text.

Please move the page number to bottom center.

Please add the title to the running header on both recto and verso pages.

Please add the act/scene to the running header flush right (on recto pages) and flush left (on verso pages).

Thanks!
