### ISSUE TITLE
Feature request: Export in-progress texts to PDF

### ISSUE THREAD

**Issue by JackWilton1594** [projectLEMDO/lemdoIssues#270]
Is it possible to generate a PDF of a modern-spelling text, without annotations or collations? Editors may find this useful when proofing and/or collating against other editions _in situ_.

**Comment by martindholmes** [comment]
This would be a lot of work. How high is it in your priority list? The print build is a completely separate process which requires the preparation of a special print XML file; your editors would have to be trained on how to do this, and would have to install all the LaTeX code needed on their machines (and couldn't be using Windows).

**Comment by martindholmes** [comment]
Also, the web view has a feature for turning off annotations and collations. I've just talked to Janelle and Navarra, and we've agreed that since there are multiple ways to view your text (author mode in Oxygen, and the complete build every couple of hours on Jenkins), it doesn't make sense to put lots of precious hours into creating yet another view of the text. For any text which is intended to go to print, as soon as the content is basically complete and the and running order is established, we can set up a print build for that text.

**Comment by JackWilton1594** [comment]
Doh! That seems so obvious now.
