### ISSUE TITLE
Check placement of question mark

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#272]
![image](https://github.com/user-attachments/assets/d27c538b-b0e9-4467-8d2a-a4aa4e34c006)

**Comment by martindholmes** [comment]
That's addressed in this ticket:

https://github.com/projectLEMDO/lemdoIssues/issues/235

where we decided to do this in the anthology build. I think we explicitly decided to do this for DRE, but not for QME, because QME would want to keep their annotation and collation markers where they put them. If we want to do the same operation for QME, then it's easy, but we can't really do it for some markers and not others. We have this code in the anthology XSLT:

~~~~~
<xsl:variable name="movePunctuationAnthIds" as="xs:string+" static="yes" select="('dre')"/>
  <xsl:variable name="shouldMovePunctuation" static="yes" as="xs:boolean" select="$anthToBuildId = $movePunctuationAnthIds"/>
  <xsl:include href="anthology_move_punctuation_module.xsl" use-when="$shouldMovePunctuation"/>
~~~~~

so all I need to do is add 'qme' to the list of anthologies to which this applies. @JanelleJenstad let me know if I should go ahead.

**Comment by martindholmes** [comment]
@JanelleJenstad Ping! :-) I just need a yes or no on this one.

**Comment by JanelleJenstad** [comment]
Yes, go ahead with the same processing for QME. Thanks!

**Comment by martindholmes** [comment]
Done in rev 19869. If the fix works for the specific example, we can close this.

**Comment by martindholmes** [comment]
I think this is now working. The annotation symbol is wrapping to the next line, but this is in the context of a prose paragraph in a speech, and there are width constraints all the way up to the `<main>` container which force a limited page-width, and mean that it must wrap after the question mark in this particular case. That's life. :-)
