### ISSUE TITLE
Make three default renderings for images

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#29]
Would you please create for us three default renderings for images in LEMDO, as we have in MoEML?

Left (float image left; text should wrap)
Centre (not sure about text wrapping; happy to do whatever MoEML already does)
Right (float image right; text should wrap)

**Comment by martindholmes** [comment]
@JanelleJenstad What are the implications for the PDF rendering? Also, what about caption location -- above or below? On narrow mobile, should they all go centred? Can you give me examples of existing images which you'd like to see rendered in each of these three modes, so I have something to test with?

**Comment by martindholmes** [comment]
@JanelleJenstad Any answers to the questions above? Until we have examples to work with, @pszpak won't be able to do anything.

**Comment by JanelleJenstad** [comment]
"What are the implications for the PDF rendering?" --> Presumably we'd want to align left, center, and align right in the PDF as well and wrap the text around the images. Most of the images are in the Stage History essays, however, which we don't include in the PDF (although given its performance-as-research approach, QME might have different thoughts on that).

"Also, what about caption location -- above or below?" --> Below seems to be more standard. 

"On narrow mobile, should they all go centred?" --> Yes.

"Can you give me examples of existing images which you'd like to see rendered in each of these three modes, so I have something to test with?" --> I have yet to add the images to the H5 edition (for the "Stage History" essay) to the repo. I'll do that while you are away so that you have something to test.

**Comment by martindholmes** [comment]
@JanelleJenstad @pszpak Over to Pat for examples of how HTML should look; once we know that, we need to decide:

1. What to do with all the existing encoded images. Presumably they can't all be manually fixed in one pass, so they'll all have to get a default rendering we can all live with.
2. How to schedule the changes, including any issues for the PDF rendering, given that various things need to be released soon.

I've just committed a change at Pat's request that ignores any `@style` on the TEI graphic element (there are 782 instances of style on graphics) and puts the width and height into their respective HTML attributes rather than in the style attribute. We'll see what the fallout is from that, and go from there. It seems we should probably remove `@style` from the `<graphic>` element, so people don't think they can use it.

**Comment by martindholmes** [comment]
My sense from the encoding point of view is that we should use `<figure>/@type` to specify these three different types of images. The reason for this is that a parent figure elements is required for any graphic which needs a caption, and is also required in order to provide alt text for an image, and since all graphics really should have alt text, and many graphics that need to be displayed in specific ways will also need captions, this is really a feature of the figure level rather than the graphic level. 

We already have the following values of `<figure>/@type` in use in OS texts for descriptive purposes:

ornament
rule
horizontal-rule
iembed (wtf???)

Disregarding the last, which must just be some ISE survival, and the horizontal-rule one, which occurs only once and could probably be just "rule", we would be looking at constraining the valList to "ornament", "rule", and the values we choose for these image layout types. I would suggest we call them "left", "centre" and "right". The issue of text wrapping is an incidental implementation question because of course there will be contexts where it can't wrap (narrow mobile views for instance); and all three must be viewed as hints rather than commands, because depending on the image size and the user-agent configuration, they may not be displayed any differently from each other.

If this makes sense to @JanelleJenstad and @Navarra-Houldin, let me know and I'll implement the valList and add some Schematron to make the first two values only available in OS texts and the other three only in critical paratexts and documentation. Then we'll have to re-process the 84 graphic elements which don't have parent figures to add them, and someone will have to add the descs to each of them for accessibility.

**Comment by martindholmes** [comment]
Summarizing my discussion with @pszpak today, for @JanelleJenstad and @Navarra-Houldin:

 - All TEI `<graphic>` elements will be required to have `@width` and `@height` attributes. Implication for the team: someone will have to add these to around 63 elements in the documentation and 529 in the text folder.
 - All TEI `<graphic>` elements will have to be wrapped in `<figure>` elements, which must have a `<desc>` child, which will provide the text for the HTML `@alt` attribute, and/or a `<figDesc>` child, which will be used for the caption (and for the `@alt` if no `<desc>` is provided).
 - Rendering will use the `@type` attribute value as a hint for how to display the image. If a figure has for example `@type="left"`, then if there is enough space in the layout, it will be floated to the left. If not, or if there is no `@type` attribute, it will be displayed centred.
 - Facsimile images will be treated in a completely different fashion, because they are initially displayed as thumbnails, and are potentially large and numerous on a single page. They will have at least two smaller sized versions, which will be pre-generated in the facsimiles folders, and an HTML `<picture>` element will be used to present them, so that they can be displayed optimally on various display formats without the need to download all the full-size versions unless they're requested by the reader.

**Comment by LEMDO-PM** [comment]
@martindholmes thanks for keeping us posted! We'll get started on adding the `@width` and `@height` attributes and the `<desc>`/`<figDesc>` elements, and wrapping `<graphic>` elements in `<figure>`.

In addition to the images in critical paratexts and OS texts, there are images in annotation files (for example, in emdH5_FM_annotation.xml). Can we use the new type values there as well, or will we need different encoding for those cases?

There are also cases that I've come across in which `<graphic>` elements have `@style` and `@rendition` attributes on them. What would you recommend we do with that? Here's an example from emdH5_FM_annotation.xml:
`
<graphic url="img:H5_Jeu_de_paume.jpg" mimeType="image/jpg" height="460px" width="346px" style="text-align:left;" rendition="rnd:lightbox">
`

**Comment by LEMDO-PM** [comment]
@martindholmes do you also want to require `@mimeType` on all `<graphic>` elements?

**Comment by martindholmes** [comment]
It's fine to use the same encoding in annotations, but because of their context they'll all be rendered centred anyway. The existing style and rendition elements will have no function, but the style att is having an effect right now, so things will change in the short term if you remove it.

**Comment by martindholmes** [comment]
Our documentation says the mime type should be there. Can't remember exactly why, though.

**Comment by LEMDO-PM** [comment]
@pszpak , see emdAHDM_GenIntro

**Comment by martindholmes** [comment]
@pszpak Just flagging up for you that this feature request had changed a bit, but the output from your point of view is the same. There will be three types of figure:

 - type="thumbnail" data-rend="left" (suitable for floating if enough space is available, and recommended to float left).
 - type="thumbnail" data-rend="right" (suitable for floating if enough space is available, and recommended to float right).
 - type="fullsize" (should always be displayed at full width).

The values for data-rend are not encoded in the XML; they are generated at build time so that they alternate in any given text, which seems the optimal approach. The thumbnail types should of course only be floated in contexts where there is space for it.

**Comment by martindholmes** [comment]
These changes including schema changes and data fixes committed in rev 12277.

**Comment by LEMDO-PM** [comment]
@martindholmes @pszpak Where are we at with this request?

**Comment by martindholmes** [comment]
@LEMDO-PM As my summary above shows, my bit is done; the attributes are being generated as in the plan, and it's up to @pszpak or you to implements the scss code.

**Comment by pszpak** [comment]
The images are now styled as are the figcaptions. Let me know if you want adjustments.

**Comment by JanelleJenstad** [comment]
Brilliant! Thank you!

**Comment by JanelleJenstad** [comment]
We made a tweak to the styling (removed the coloured border). Otherwise, we think it looks good!
