### ISSUE TITLE
Search repo for any files that have both ldtBornDig and ldtPrimary

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#40]
Please search the repo for any files that have both ldtBornDig and ldtPrimary.  

If there aren’t any, please write Schematron to:

1. make them mutually exclusive categories.   
2. require every file (except documentation files, which are rooted on div) have either ldtBornDig or ldtPrimary

**Comment by martindholmes** [comment]
There are no files with both, so I've added the Schematron to make them exclusive, and fixed the problem of the `@type` values "Greg" and "Call" being added directly to the ODD file instead of to TAXO1. However, the following 35 files have neither, so before we can make the presence of one of them a requirement, they'll have to be fixed:

emd1H4_M
emd2H4_M
emdAdo_M
emdAHDM_M
emdAWW_M
emdAYL_M
emdCB_M
emdCnC_M
emdCym_M
emdEdw_M
emdErr_M
emdFBFB_M
emdFEm_M
emdHam_Q1M
emdHick_M
emd2HW_M
emdINTE1_M
emdJC_M
emdKNDW_M
emdLeir_M
emdMac_M
emdMan_M
emdMM_M
emdMV_M
emdOFG_M
emdOFG_O
emdOWT_M
emdPer_M
emdRho_M
emdSel_M
emdTim_M
emdTN_M
emdTRIU3_M
emdTRKJ_M
emdYth_M

Assigning the ticket back to you both; when those fixes are in, let me know and I'll add the other Schematron rule.

**Comment by JanelleJenstad** [comment]
Thanks @martindholmes! @Navarra-Houldin is going to add ldtPrimary to all of these files (which, weirdly, are all primary texts).

**Comment by Navarra-Houldin** [comment]
@martindholmes, I have added ldtPrimaryText to all of these files.

**Comment by JanelleJenstad** [comment]
@martindholmes: We are ready to the implement the Schematron requested in this ticket.

**Comment by martindholmes** [comment]
Done in rev 10748.
