### ISSUE TITLE
Consider changing ldtPrimaryApparatus to ldtBornDigParatextCollation

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#41]
The principal fork in LEMDO processing and rendering is the distinction between ldtBornDig and ldtPrimary

Collation files have been niggling away at me for a while. Are they really primary, I've been wondering? We originally put them in primary because the lemmas and the readings are short quotations from primary texts. James, Sarah, and Brett (my advisors on textual matters) confirmed that they are a form of critical paratext. I suggest that we leave things AS IS unless our decision to categorize them as ldtPrimaryApparatus is making our processing more complicated than it needs to be. If it would be better for processing purposes to have them be born digital, then the time to make the change is now.

Can you do the following:

1. Check to see where our processing and schematron might be looking for ldtPrimaryApparatus and see what dependencies might pertain.
2. If making this change would simplify our processing, then let's recategories collations. 
3. If we can make (and want to make) this change, do a global find-and-replace in the lemdo/data/texts folder.
4. Update the taxonomy and regenerate the schema. 

Timeline: If this change is desirable and possible, it should be in place _before_ Pat gets back to work on the LEMDO and MoMS designs. 

@JanelleJenstad will update the documentation and the templates.

**Comment by martindholmes** [comment]
@JanelleJenstad The only mentions of ldtPrimaryApparatus in the ODD file are in the elementSpecs for relatedItem and span, where remarks say: "This element is only used in the context of a document in the cat:ldtPrimaryApparatus category." As it happens, although collation files do contain relatedItem, none of them contain span elements at all; and there are 142 non-apparatus files which contain relatedItem. So I believe these remarks are just wrong.

There's no Schematron using this category specifically, nor is there any XSLT that references it. So in theory we could just switch. But the result of that would be that these (currently 59) collation files would be processed as bornDig rather than primary, which might change some of the output from them. Can't easily tell until we try. This is exactly the sort of thing that I'd do in a git branch if I could. :-)

Since you need this to be in place before Pat comes back, I'm going to do it today, and we'll have to live with any unexpected fallout.

**Comment by martindholmes** [comment]
Curses, I found some Schematron... might have to roll back.

**Comment by martindholmes** [comment]
Easy fix in the Schematron. I've made the change in rev 9958, and we'll see what falls out. This of course affects some of the annotation files as well as the collations, because 17 of them had the wrong cat. I've fixed those in rev 9959.

**Comment by martindholmes** [comment]
Done, and all fallout now appears to be fixed.
