### ISSUE TITLE
Tweak Broken Link Diagnostics

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#44]
The broken link diagnostic is turning up links that are encoded correctly and work when rendered. The issue is coming up for links to images and links to chapters of documentation

Example of diagnostic report for image links:
learn_subversion (3)

    img:svnStatus.JPG
    img:svnCommitMessage.JPG

Example of diagnostic report for links to chapters:

learn_quickStartEncoder (9)

    doc:learn_printChapter
    doc:learn_msChapter
    doc:learn_modernChapter
    doc:learn_annotationsChapter
    doc:learn_paratextsChapter
    doc:learn_collationChapter
    doc:learn_encodingGuidelinesGeneral
    doc:learn_encodingGuidelinesQuotations
    doc:learn_makingLinks

**Comment by martindholmes** [comment]
The doc: links are showing as broken because these documents don't actually exist in the source; they're the chapters inside the lemdo.odd file. Should be able to add those div ids as valid targets. The img ones are weird; I would have expected all the image links to fail, or none of them. But I notice both of these have upper-case file extensions, which we shouldn't ever do; I'm going to fix those file extensions and the links to them before I do anything else.

**Comment by martindholmes** [comment]
Upper-case file extensions have now been fixed in rev 10232. We may see some fallout from this on systems which don't properly distinguish between upper- and lower-case in filenames, but that's the precise reason why we try to be strict about the use of case in file and folder names in the repo.

**Comment by martindholmes** [comment]
OK, fixing the bad file extensions clears those two issues off the list. I've added Schematron to prevent the use of upper-case extensions for images, but I can't rebuild the schema right now because the TEI site is down AGAIN, and our schema build process has a bug which makes it dependent on the p5subset.xml from the TEI site. I'm going to raise another issue for that.

**Comment by martindholmes** [comment]
The documentation link issue is fixed in rev 10234. Closing.

**Comment by martindholmes** [comment]
Schematron now built into the schema,

**Comment by JanelleJenstad** [comment]
How do we link to chapters whose xml:ids are defined in the ODD file then?
`<ptr target="xmlid">` without the doc: prefix?

**Comment by martindholmes** [comment]
@JanelleJenstad I don't understand the question. The fix worked, and those links no longer show up in the diagnostics. If there's an existing problem you can point at, could you open a fresh ticket with details?
