### ISSUE TITLE
Standardize rendering of Prologue and Epilogue line numbers

### ISSUE THREAD

**Issue by Navarra-Houldin** [projectLEMDO/lemdoIssues#51]
We noted that `<ptr>`s pointing to lines in epilogues and prologues render differently in print and in HTML. E.g., in the PDF it's "Epilogue.12", while in the HTML it's "Epilogue 12".

We want it to render with a space (no period).

**Comment by martindholmes** [comment]
I've committed an attempted fix for this, but I'm unable to build and check the PDFs because of encoding problems in H5 and Oth. H5 has:

~~~~~
     [java] ERROR: The following references were not found in the bibliography files: 
     [java] OEDT3
     [java] THEO4
     [java] Terminating the build.
~~~~~

while Oth has:

~~~~~
     [java] Processing ptr target emdOth_M_anc_171
     [java] 
     [java]         The text includes a ptr element pointing at id emdOth_M_anc_171
     [java]           but there is no such element in the text.
~~~~~

@JanelleJenstad @Navarra-Houldin could you  look into this so we can test the PDF builds and see if my fix is working?

**Comment by martindholmes** [comment]
The H5 problems seem to be a strange artifact of working on my laptop, and Jenkins has build the H5 PDF successfully. I believe this is fixed, so I will close, but please re-open if you find any issues.

**Comment by Navarra-Houldin** [comment]
It looks great, thanks @martindholmes!
