### ISSUE TITLE
Text is scrolling under menus

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#74]
![image](https://user-images.githubusercontent.com/5943608/200921436-2c5b335d-99d9-4496-91b6-4928807a4943.png)

Hi Pat,
I noticed this bug on the MoMS site. It's happening on all the anthologies.

**Comment by JanelleJenstad** [comment]
Also note this behaviour:

![image](https://user-images.githubusercontent.com/5943608/200922162-17644795-071a-477b-a7d4-5b4a9c41913d.png)

**Comment by martindholmes** [comment]
I see this on MOMs but not e.g. on QME.

**Comment by pszpak** [comment]
I did fix the the first issue by adding a background colour (other than the current transparent), but not the second issue because:

Before I get into the css of mayoral shows we'll nail down the look this week (in the form of a mockup for things like color, logo, and splash page). It'll then be implemented and we can then squash css rendering problems that occur with that design.
