### ISSUE TITLE
MoMS Mobile Site Issues

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#97]
Mobile specific: The MoMS homepage's coat of arms is very large and covering the main image. The homepage button (the MoMS logo in the top left) is covered by an extended search box when you click it in Firefox, but is working on Chrome and Safari.
![MoMS Mobile](https://user-images.githubusercontent.com/116194494/208493645-5fdefd9b-eac8-4f29-9a1d-69b3c557dcad.png)

**Comment by martindholmes** [comment]
@LEMDO-PM Pat's on vacation now, so not much chance we can fix this. I can have a look, but he probably won't want me messing with it. What device did you take the screenshot on?

**Comment by martindholmes** [comment]
I can see the rule he intended to cover this, but it doesn't seem to be working:

~~~~~
.splash-crest {
	width: 755px;
	@include bp-768(){
		width: 150px;
	}
	height: auto;
	left: 50%;
	transform: translate(-50%, -50%);
	position: absolute;
}
~~~~~

Trying to figure out why that breakpoint is failing now.

**Comment by LEMDO-PM** [comment]
The screenshot is from my Windows laptop, but it looks the same on my Android phone.

**Comment by martindholmes** [comment]
I just can't figure out why the include/mixin isn't working, but I've added a temporary override that limits the width of the crest to 20% of the screen width; that seems to basically do the job. There's something strange about the way mixins are handled in the MoMS SCSS as opposed to the regular lemdo-dev; the parentheses following the mixin name seem wrong to me. @pszpak can you look at this when you get a chance? If you remove my width setting from the splash-crest ruleset you'll see the weird behaviour. Meanwhile we should be able to release with my fix.

**Comment by LEMDO-PM** [comment]
Alright, thanks Martin!

**Comment by JanelleJenstad** [comment]
I think the large crest on the mobile site might be intentional. I like it as it is. But the not returning to the home page is a bit of a problem.

**Comment by martindholmes** [comment]
The large crest is definitely unintentional; @pszpak's code says so. The puzzling thing is why the code isn't working, but the fix I did yesterday appears to be doing the job for now; @JanelleJenstad @LEMDO-PM can you confirm this particular issue is OK now? If so, we can demote this ticket to non-urgent and @pszpak can deal with it when he gets back. There are a couple of other mobile issues I'm going to look at next.

**Comment by LEMDO-PM** [comment]
Yes, that seems to have made the coat of arms smaller. The only issue that I still have is that when I'm on a page other than the homepage, clicking on the logo in the top left seems to expand the search bar rather than bring me to the homepage. I've attached a screenshot from the Firefox browser on my Android phone of what happens when I click the logo.
![MoMS Logo - Copy](https://user-images.githubusercontent.com/116194494/208710046-ef119db1-c82b-42c4-b75a-81e10aa53fa5.jpg)

**Comment by martindholmes** [comment]
I hadn't seen this problem before today, but I've put in place a temporary fix. The issue seems to be only on Firefox, in mobile view. When you click/touch in the header, the logo disappears in order to make room for the expansion of the search box, but unfortunately that also happens if you click directly on the logo, and it happens prior to the activation of the link; that gives you no way to get back to the home page.

I've implemented a temporary fix in lemdo-dev.scss, in rev 11968, by adding this:

~~~~~
/* MDH 2022-12-21: Temporary fix for Firefox bug on mobile, whereby
   the logo disappears when you click on it, before the link is 
   activated. See GitHub issue #97, second main topic. */
div#topBar:focus-within > header:focus-within {
  display: flex;
}
~~~~~

This is not a perfect fix because there's a brief jiggle of the position of the search box when you click on the logo, but the link works and the home page is accessible, so @pszpak will need to look at it when he gets back. I'll remove the urgent label and assign it to him.

**Comment by pszpak** [comment]
I've fixed both these issues now.
