### ISSUE TITLE
Font inconsistencies on the MoMS site

### ISSUE THREAD

**Issue by LEMDO-PM** [projectLEMDO/lemdoIssues#99]
We've noticed a few font inconsistencies on the MoMS site. I'll attach screenshots (all taken in a Firefox browser on my Windows pc).

- From the collation popup accessed from emdDEVI3_M with encoding in emdDEVI3_M_collation
![Collation Popup Font](https://user-images.githubusercontent.com/116194494/209029147-31d358fc-651e-4235-adf1-73aee11c89c2.png)

- From emdDEVI3_M_collation (accessed on the apparatus page, not as a popup in the modern file):
![Collation Font](https://user-images.githubusercontent.com/116194494/209028517-648c5171-f44b-4e3e-a425-e4e9e5cb3088.png)

- Font in popups from links to PERS1 looks different from font in popups from links to ORGS1
PERS1 font:
![PERS1 Font](https://user-images.githubusercontent.com/116194494/209029532-d522585a-dacd-4946-b465-fff2d7e2f9af.png)
ORGS1 font:
![ORGS1 font](https://user-images.githubusercontent.com/116194494/209029588-14dfe4f1-d738-4150-bb2f-147072054403.png)

- Fonts in links show up sans-serif (not sure if this was intentional?) example taken from DEVI3_M_annotation
![Ref fonts](https://user-images.githubusercontent.com/116194494/209029762-06cb5625-10d1-464c-976e-cb3bd79df623.png)
Note that some of these are `<ref>` elements linking to BIBL and some are localCit.

**Comment by martindholmes** [comment]
On the three issues:

1. Differences between the collations page itself and collations as they show up in the text: Nobody on the programming team ever expected annotation and collation files to be published at all, so it was a surprise the other day to find them linked from the edition page. I did a quick fix to make links work on that page, and rather than start the long discussion we'll need to have to all agree on what a collations-only page should look like, I just wanted to make it work. If you can give me a detailed spec for exactly how each component of that page should look within the next couple of hours, I can have a go at implementing it, but the fact that things just look different in two different contexts isn't enough to go on. Should they even look the same at all? Would that make sense?

**Comment by martindholmes** [comment]
2. Differences between the popup styling for people and orgs:

The heading style is due to a bug in the CSS, which I'll fix. The difference in the text size is due to the person elements having a p inside the note element, where the orgs don't. I'm going to investigate that now.

**Comment by martindholmes** [comment]
OK, Fixes for both of the number 2 issues now committed.

**Comment by LEMDO-PM** [comment]
Thanks. I'll take a look at the collations and see if I can think of any options. My concern is less that the collation page and the collation popup look different from each other and more that there are different font sizes (and possibly different fonts for `<rdg wit>` and `<lem source>`) within the popups and there are different fonts within the collation page.

**Comment by martindholmes** [comment]
3. Sans-serif font used for linked references in born-digital texts:

This is the rule which makes this so:

~~~~~
body[data-catrefs*="BornDig"] main a:link, body[data-catrefs*="BornDig"] main a:visited {
  color: var(--link-color);
  text-decoration: underline;
    text-decoration-color: currentcolor;
    text-decoration-thickness: auto;
  text-decoration-color: var(--link-text-decoration-color);
  text-decoration-thickness: 1px;
  transition: all 0.3s ease-in-out;
  cursor: pointer;
  line-height: var(--lineHeightPrimarySourceModern);
  font-family: var(--primarySans);
}
~~~~~

As you can see, it's very explicit and intentional, so either it follows a request from the team, or it's part of @pszpak 's design, so I don't think this is a bug. And in fact I think it looks nice, and serves to distinguish linked references from the surrounding text in a useful way. So I don't propose to do anything about this at the moment. If you don't like it and the rest of the team agrees it should be changed, then I think this should be a new ticket assigned to @pszpak for when he's back. I don't think it should delay the MoMS release.

**Comment by LEMDO-PM** [comment]
In lemdo-dev.css, rdg does not have the same styling that lem does.
For rdg:
`div[data-el="rdg"],
div[data-el="note"] {
	margin-bottom: .5rem;
}`

For lem:
`div.popup div[data-el="lem"] {
	margin-bottom: .5rem;
	font-family: var(--noteFont);
	font-size: var(--noteSize);
	font-weight: 400;
	color: var(--noteColor);
}`

If we made them the same, would that fix the inconsistencies in size/font in the collation popups?

**Comment by JanelleJenstad** [comment]
Yes, it would. (And let’s not worry about the inconsistencies on the collations page. Getting the pop-ups consistent is much more useful.)

**Comment by martindholmes** [comment]
Traditionally, lem and rdg should be displayed differently, no? It's important to distinguish between them.

**Comment by martindholmes** [comment]
On problem 1, as well, note that the way the popup behaves in adding the witness information at the bottom of the other stuff is not going to work for the all-collation-only-collation page, because that's a long list of collations; the witness info has to be added below the specific collation item that's being displayed, otherwise it wouldn't be visible. I indented it to make it distinct. I think it's such an odd thing to list collations without context like this that it will require serious thought to decide how they should be displayed.

**Comment by martindholmes** [comment]
Also, note that the page as it is currently generated does not have a wrapper element for lems and rdgs that belong together, so there's nothing to say where one collation entry begins other than the presence of a lem. I was thinking we could at least make it look a bit cleaner by adding a line between entries, but that can only be done by adding a top border to lems. Would that be a good idea?

**Comment by LEMDO-PM** [comment]
I think that a top border would be nice. As far as where the witness info is displayed on the collations-only page, let's defer that for after this release.

**Comment by LEMDO-PM** [comment]
> Traditionally, lem and rdg should be displayed differently, no? It's important to distinguish between them.

1. Our rdg styling doesn't specify popup as the lem styling does. Does it need to?
2. As far as I could tell, our rdg styling also doesn't specify font/size. Should it?
3. If we want witnesses and readings to appear differently, I think that using font would be more effective than using size to show that they are different. Perhaps if we used `font-family: 'primarySans'` for readings and keep witnesses as they are? @JanelleJenstad, do you have a preference?

**Comment by martindholmes** [comment]
I don't think we should be trying to second-guess @pszpak 's design decisions at this stage. I think things look as he intended, and I think they look good; we should be looking for bugs at this stage, not re-inventing the design. I've just committed a change that will add a border line between collation entries on the all-collations-only-collations pages, which at least clarifies which lems and readings belong together; that should be enough for now, I think. I'm pretty sure he had no idea that such a page was going to be published, so he wouldn't have worked on that, but when he's back he'll do a proper job on it.

When you're reading the CSS, remember that it's a cascade; just because a specific ruleset doesn't specify a font size doesn't mean that there isn't a font-size in effect (there always is), and also doesn't mean that someone omitted it by mistake. If the in-effect font-size setting isn't explicitly overridden, that just means that the designer intended the inherited font-size to remain in effect.

**Comment by LEMDO-PM** [comment]
That sounds good. Thanks Martin!

**Comment by JanelleJenstad** [comment]
Print convention is to put a ] (closing square bracket) after the lemma. Because we’re digital, we give the words “this edition”
or the siglum. We don’t need a typographical distinction. Let’s keep things simple and make lemma and rdg the same for now.

**Comment by JanelleJenstad** [comment]
Yes, let’s leave things be!

Sent from my iPhone

On Dec 22, 2022, at 9:10 AM, LEMDO-PM ***@***.***> wrote:

﻿
Notice: This message was sent from outside the University of Victoria email system. Please be cautious with links and sensitive information.


That sounds good. Thanks Martin!

**Comment by martindholmes** [comment]
@LEMDO-PM Could you triage what we've discussed and open new tickets for Pat for any remaining issues that he'll need to deal with when he's back? Then we can close this one.

**Comment by LEMDO-PM** [comment]
Yes, I'll do that now. Thanks @martindholmes !

**Comment by LEMDO-PM** [comment]
I've created Issue #101. Closing this one now.
